### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by MarlonJrBM** [exercism/cpp-test-runner#36]
Dear contributors,

It seems the first two links shown in this repository's README.md are broken:

> This test runner, much like the ones for other tracks, must respect the [specified interface](https://github.com/exercism/automated-tests/blob/master/docs/interface.md).
> 
> Since the test runners are deployed as Docker images the [related specification](https://github.com/exercism/automated-tests/blob/master/docs/docker.md) must be respected for the Dockerfile.

It would seem they point to a repository which has been deprecated and replaced by [this one](https://github.com/exercism/docs).

I tried to fix this myself but the folder structure in new repository is not at all familiar to me. Does anyone know what the new links are supposed to be? Maybe other repo's READMEs are also affected?

Let me know if I can be of any help.

Thanks,

**Comment by ErikSchierboom** [comment]
@MarlonJrBM A fix would be much appreciated! The repo you're linking to is indeed the correct on and its contents are rendered on https://exercism.org/docs. I'd link to the documents on the https://exercism.org/docs/ pages, so:

The interface: https://exercism.org/docs/building/tooling/test-runners/interface
The specification: https://exercism.org/docs/building/tooling/test-runners/docker

If you find this issue in other repos, a fix would be most appreciated there too!

**Comment by ErikSchierboom** [comment]
@MarlonJrBM FYI: there is an open PR for this repo: https://github.com/exercism/cpp-test-runner/pull/35#pullrequestreview-748905418 So maybe you could fix this in other repos?

**Comment by MarlonJrBM** [comment]
Alright, I can try. Exercism's has 287 repositories, so that can be a somehow daunting task.  It seems not all repositories have broken links though, so it might not be that hard after all.

Should we leave this issue open meanwhile?

**Comment by ErikSchierboom** [comment]
@MarlonJrBM No worries, I created a small bash script to find the occurences of markdown files that were still referring to the `exercism/automated-tests` repo:

https://github.com/exercism/bash-test-runner/blob/main/README.md
https://github.com/exercism/cpp-test-runner/blob/main/README.md
https://github.com/exercism/csharp-test-runner/blob/main/README.md
https://github.com/exercism/elixir-test-runner/blob/main/README.md
https://github.com/exercism/fortran-test-runner/blob/main/README.md
https://github.com/exercism/fsharp-test-runner/blob/main/README.md
https://github.com/exercism/generic-test-runner/blob/main/README.md
https://github.com/exercism/groovy-test-runner/blob/main/README.md
https://github.com/exercism/haxe-test-runner/blob/main/README.md
https://github.com/exercism/javascript-test-runner/blob/main/README.md
https://github.com/exercism/lua-test-runner/blob/main/README.md
https://github.com/exercism/ocaml-test-runner/blob/main/README.md
https://github.com/exercism/prolog-test-runner/blob/main/README.md
https://github.com/exercism/purescript-test-runner/blob/main/README.md
https://github.com/exercism/rust-test-runner/blob/main/README.md
https://github.com/exercism/sml-test-runner/blob/main/README.md
https://github.com/exercism/swift-test-runner/blob/main/README.md
https://github.com/exercism/tcl-test-runner/blob/main/README.md
https://github.com/exercism/typescript-test-runner/blob/main/README.md
https://github.com/exercism/vimscript-test-runner/blob/main/README.md

**Comment by MarlonJrBM** [comment]
Wow, amazing! That's much better than 287 repositories. I will get into it this task soon!

**Comment by MarlonJrBM** [comment]
I will also make sure to follow the tip you posted on [](https://github.com/exercism/cpp-test-runner/pull/35)

**Comment by ErikSchierboom** [comment]
Brilliant!

**Comment by peterschussheim** [comment]
#35 updates the docs for this repo, cpp-test-runner; since these changes need to be merged to each repo listed in https://github.com/exercism/cpp-test-runner/issues/36#issuecomment-916072431, we can track the progress here, or if @ErikSchierboom has a preference, please let us know.

@MarlonJrBM I'd be happy to help you complete the updates:

- [ ] https://github.com/exercism/bash-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/cpp-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/csharp-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/elixir-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/fortran-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/fsharp-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/generic-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/groovy-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/haxe-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/javascript-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/lua-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/ocaml-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/prolog-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/purescript-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/rust-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/sml-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/swift-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/tcl-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/typescript-test-runner/blob/main/README.md
- [ ] https://github.com/exercism/vimscript-test-runner/blob/main/README.md

**Comment by MarlonJrBM** [comment]
Ok Peter, I will start from the bottum-up then ! (vimscript, typescript, etc,etc ). Thanks !

**Comment by MarlonJrBM** [comment]
My own list which I will be editing in-place:

**In progress**:

- Rust
- PureScript

**Checked-in**


----------------------------------------------------------------------
To be honest with you, I will not be able to work at on this during the weekend -- only from Monday onwards. So if you want to, you can do the rest (I hope you enjoy your weekend anyway)!

Also, I could not find any broken links for many of the above repos (such as vimscript, typescript, etc,etc). Are these repos okay, or am I really tired and I missed something?

**Comment by ErikSchierboom** [comment]
Thanks both!
